### ISSUE TITLE
Suggestion/Request: add more other SV caller using long reads

### ISSUE THREAD

**Issue by tjiangHIT** [stat-lab/EvalSVcallers#1]
Congratulations to you for paper publishing and thanks for your great work! 
You evaluate plenty of tools and give a lot of helpful viewpoints for choosing SV callers. However, in your benchmarks, only 3 approaches (sniffles, pbsv and pbhoney) are used for evaluation. I think a comparison analysis with more other existing tools using long reads will be helpful (e.g. [SVIM](https://github.com/eldariont/svim), a newer caller for SV detection; [rMETL](https://github.com/tjiangHIT/rMETL), a non-reference MEI detector.).  In a sense, it is difficult to search SV callers based on 3rd generation sequencing compared with NGS. 

Hope your reply!
Tao

**Comment by stat-lab** [comment]
Dear Tao,

Thank you for your comment. New SV callers will be developed and new versions of existing tools will be updated after our paper has been published. We will make an effort to continue updating our evaluation results, integrating results of new SV callers, and to present them at this site.

**Comment by tjiangHIT** [comment]
Hi @stat-lab , 
Thanks for your prompt response! It is a valuable work for promoting developing SV callers with higher sensitivity and accuracy. Looking forward to your update.

Cheers!
Tao

**Comment by Tintest** [comment]
Hello,

I approve @tjiangHIT's request to add more long reads SV caller. If you could add [SVIM ](https://github.com/eldariont/svim )and [NanoSv ](https://github.com/mroosmalen/nanosv) in your tool list it would be great !

Regards.
