### ISSUE TITLE
Seeking help with F measure statistical analysis

### ISSUE THREAD

**Issue by Mkddb** [stat-lab/EvalSVcallers#15]
Hello Team,

Sorry for the off topic again. 
I am stucked at the "F measure analysis".
I follwed the similar instructions to find the "nF (normalized F measures) as given in the manuscript. still getting the "final nF values" with a difference of ratio of 1.5 times for Deletion category. can you please check the analysis below and assist me to sort out the discrepancy. 
I have taken the raw data from Supplementary Table S19.

[F measure analysis.xlsx](https://github.com/stat-lab/EvalSVcallers/files/5573674/F.measure.analysis.xlsx)
[F measure analysis.pdf](https://github.com/stat-lab/EvalSVcallers/files/5573688/F.measure.analysis.pdf)

**Comment by stat-lab** [comment]
The mean F-measures were calculated with the F-measures of all the tools (a total of 69 tools). The presented in Table S19 are from only good tools.
The tools used in your analysis seem to be only those included in Table S19.

**Comment by Mkddb** [comment]
Thanks for the clarification. 

Yes, i tried with the tools in Table S19 and calculated the mean for the corresponding category, say tools given in S19 for Deletion. 
It would be really helpful, if the list/table of F-measures of all the tools (69 tools) can be shared for all SV categories from which mean F measure to be calculated. or the final mean F-measure value for all SV categories ? 

Thanks in advance.

**Comment by stat-lab** [comment]
That can be done with the data of another supplementary Tables in our paper.

**Comment by Mkddb** [comment]
Which tables ? please specify, if possible.

**Comment by stat-lab** [comment]
Tables S5-S9.

**Comment by Mkddb** [comment]
Thanks for the informaion. It was really helpful.
