### ISSUE TITLE
Parameters used for aligning short and long read data?

### ISSUE THREAD

**Issue by joshuak94** [stat-lab/EvalSVcallers#2]
Hello,

I'd like to use the scripts here to compare another structural variant caller, [Vaquita](https://github.com/seqan/vaquita). However, I would like to recreate the datasets as exactly as possible. I've downloaded the same short read sets (data1 to data4), but the paper only says that they were aligned with bwa. Am I right in assuming the following commands:
```sh
bwa aln hs37d5.fa ERR174336_1.fastq.gz > ERR174336_1.sai
bwa aln hs37d5.fa ERR174336_2.fastq.gz > ERR174336_2.sai
bwa sampe ERR174336_1.sai ERR174336_2.sai ERR174336_1.fastq.gz ERR174336_1.fastq.gz > ERR174336.sam
```

**Comment by stat-lab** [comment]
Dear Joshua,

I recommend to use the bwa men command as follows:

bwa mem [indexed reference fasta] [read_1.fastq.gz] [read_2.fastq.gz] -t <number of threads> -M > out.sam

Best,

Shunichi Kosugi

**Comment by joshuak94** [comment]
Thank you! I realized I was using an older version of bwa which didn't have the mem command.

Could you quickly confirm the version used by your group?

**Comment by stat-lab** [comment]
The version of bwa we are using is 0.7.13.
