### ISSUE TITLE
Inconsistency of output files

### ISSUE THREAD

**Issue by gamzemdn** [stat-lab/EvalSVcallers#21]
Hi Dear Kosugi,

When I analyse output files I see that caller.TF file has true positive INS type variants but caller.eval file shows lines in below:
INS
        	<Number of supporting reads>
        	2	3	4	5	6	7	8	9	10	12
Call   (A)	43390	12809	3529	1385	779	579	500	458	425	348	
Recall (A)	3	2.6	2.4	2.2	2.1	1.9	1.7	1.6	1.5	1.2	
Precis (A)	0.9	2.8	9.4	22.5	37.4	45.7	48.4	48.6	48.9	47.9	

convert:

'/home/gamze/Downloads/EvalSVcallers-master/scripts/convert_SV_callers_vcf.pl' -t BreakDancer '/home/breakdancer.vcf' >breakdancer.vcf

overlap:

'/home/gamze/Downloads/EvalSVcallers-master/scripts/evaluate_SV_callers.pl' **-r N** '/home/gamze/Downloads/EvalSVcallers-master/breakdancer.vcf' -of 3 >breakdancer_overlap.vcf

Why I only see A here not SS, S, M , L like in the other types? For example how can I interpret Recall(A) in terms of size?
Best Regards,
![breakdancer6](https://github.com/stat-lab/EvalSVcallers/assets/81433698/25fe6166-54da-4aee-b01d-d1e9fb7b9e00)

**Comment by stat-lab** [comment]
Most SV calling tools with short read cannot accurately detect INS sizes, especially those larger than read length. So, our script for INS evaluation does not evaluate precision and recall according to the size of the INS, but only determine them for INS breakpoints.
