### ISSUE TITLE
About different reference file than NA12878 and NA19240

### ISSUE THREAD

**Issue by gamzemdn** [stat-lab/EvalSVcallers#23]
Hello,

I am analysing different samples and using EvalSVCaller for comparison. I downloaded different reference/gold/high confidence datasets for different samples i.e. hg00514, na34285 etc. I am using reference data of these samples with -r option but results are not satisfying (all FPs). Should I preprocess reference files too before using them? If so, how can I perform that? If that is not the reason, would you suggest anything?

Another question is how can I get False Negatives?

Thanks in advance,

**Comment by stat-lab** [comment]
Does your output show the reference SV counts (i.e., Ref-DEL: Ref-INS: etc.)?
Could you show the first five lines (excluding header lines) of the reference SVs you used?

For false negative calls, you can output true positive calls using the option '-of 1'. You need to obtain false negative calls from the reference SVs that the true positive calls do not match/overlap by yourself.

**Comment by gamzemdn** [comment]
Hello and thank you for your quick response.

One of the reference files I use for my samples is named "HG00514_CHS_bionano_DLE1_annotatedSV_filtered_nonredundant.vcf" and the EvalSVcaller outputs this:

Ref-DEL: 1198	tinny (<= 100 bp): 0	short (<= 1.0 kp): 318	middle (<= 100 kb): 866	large (> 100 kb): 14
Ref-INS: 2748	short (<=1.0 kp): 944	middle (<= 100 kb): 1790	large (> 100 kb): 14
Ref-DUP: 42	short (<=1.0 kp): 0	middle (<= 100 kb): 32	large (> 100 kb): 10
Ref-INV: 29	short (<=1.0 kp): 0	middle (<= 100 kb): 20	large (> 100 kb): 9
<< HG00514_CHS_bionano_DLE1_annotatedSV_filtered_nonredundant >>

Here I paste a few lines from SV reference file for this particular sample:

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG00514

chr1	780303	SMAP10	N	<INS>	20	PASS	SVTYPE=INS;END=816393;SVLEN=2253;CIPOS=-3282,3282;CIEND=-1315,1315;EXPERIMENT=1	GT	0/1

chr1	730721	SMAP13	N	<DUP>	.	PASS	SVTYPE=DUP;END=912049;SVLEN=181328;CIPOS=-8167,8167;CIEND=-14454,14454;EXPERIMENT=1	GT	./.

chr1	667970	SMAP14	N	<INS>	20	PASS	SVTYPE=INS;END=667970;SVLEN=3576;CIPOS=-4109,4109;CIEND=-4109,4109;EXPERIMENT=1	GT	0/1

chr1	821481	SMAP18	N	<DEL>	10.0	PASS	SVTYPE=DEL;END=821681;SVLEN=-714;CIPOS=-3773,3773;CIEND=-3973,3973;EXPERIMENT=1	GT	0/1

chr1	730721	SMAP20	N	<DUP>	.	PASS	SVTYPE=DUP;END=859003;SVLEN=128282;CIPOS=-8167,8167;CIEND=-12113,12113;EXPERIMENT=1	GT	./.

chr1	870595	SMAP24	N	<INS>	20	PASS	SVTYPE=INS;END=870595;SVLEN=3874;CIPOS=-11592,11592;CIEND=-11592,11592;EXPERIMENT=1	GT	0/1

chr1	1253724	SMAP27	N	<INS>	3.01	PASS	SVTYPE=INS;END=1253724;SVLEN=659;CIPOS=-9312,9312;CIEND=-9312,9312;EXPERIMENT=1	GT	0/1

chr1	1300687	SMAP28	N	<INS>	20	PASS	SVTYPE=INS;END=1423440;SVLEN=5661;CIPOS=-20656,20656;CIEND=-13393,13393;EXPERIMENT=1	GT	1/1

**Comment by stat-lab** [comment]
The SV reference seems to be based on GRCh38. Is your test SVs from the same human reference build? (Do the chromosome names have the 'chr' prefix?)

**Comment by gamzemdn** [comment]
Yes, my reference file is "GRCh38_full_analysis_set_plus_decoy_hla.fa"

**Comment by stat-lab** [comment]
Could you show the first five lines (excluding header lines) of your SV vcf file tested?

**Comment by gamzemdn** [comment]
Hi again. I am sharing the SV vcf file from manta run:

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG00514
chr1	66365	MantaINS:1:0:0:1:1:0	AATATAATATATAA	ATATATATATTATTATATAATATAATATATATTATATAATATATTTTATTATATAATATAATATATATTATATAATATAATATATTTTATTATATAATATATATTATATTATATAATATAATATATATTAATATAAATATATATTAT	999	MaxDepth	END=66378;SVTYPE=INS;SVLEN=146;CIGAR=1M146I13D	GT:FT:GQ:PL:PR:SR	0/1:PASS:999:999,0,999:13,0:71,66

chr1	831213	MantaDEL:14:0:1:0:0:0	C	<DEL>	418	PASS	END=833732;SVTYPE=DEL;SVLEN=-2519;CIPOS=0,3;CIEND=0,3;HOMLEN=3;HOMSEQ=TGC	GT:FT:GQ:PL:PR:SR	0/1:PASS:418:468,0,999:124,10:84,19

chr1	998763	MantaINS:25:0:0:0:0:0	GC	GGGGAGGGCGCGGAGCGGAGGGGAGGGCGCGGAGCGGAGGGGAGGGCGCGGAGCGGAGG	999	PASS	END=998764;SVTYPE=INS;SVLEN=58;CIGAR=1M58I1D	GT:FT:GQ:PL:PR:SR	1/1:PASS:110:999,113,0:0,0:0,47

chr1	1207339	MantaDEL:36:0:0:0:0:0	GGAGACTGTCCTATGTCTTTCTGAGCCTCAGTTTCCCCTGTGGGCACCGAGGGGTTCTGGGACCCTGCCTCCACCAGGAAGCCTCCCTGGATTGCCCAGCCCTGCTTCTGCGCCGTCCAGCACAGGTGGAGACCCCCATGAATGCTGGGGGTGGGGGCTCTCGGGAACGTGAGCGTGGATGTGGTTCAACACCCTTTTGAGACCTGCAGCCACCGCCTCACCCCGTAAGGCGGTTCCTCCTTTTCCAAGGTAAATGACAGGAATTAGCTGTTTGTGACACCCCGGAGTTCTCAAATCCAAGATGTAGGAGCCTGCCTTGGAGAGGCAGCCCTCAGACACTGCAGAGAAGGAAGGGGTCTCTGCAGCTCCAGGCCGCCCCGACGCTCGGAAGGAAAGGGGTGGGGCCAGCTGGGCCTGGGGGC	G	867	PASS	END=1207760;SVTYPE=DEL;SVLEN=-421;CIGAR=1M421D	GT:FT:GQ:PL:PR:SR	0/1:PASS:588:917,0,585:40,33:25,20

chr1	1226336	MantaDEL:62:0:0:0:0:0	CCTGTACGGTCAGGAGGAAACATGGCACCTCCCCTCTGGGGGCTCTTTCCAGAAACCCTCAACCC	CT	303	PASS	END=1226400;SVTYPE=DEL;SVLEN=-64;CIGAR=1M1I64D	GT:FT:GQ:PL:PR:SR	0/1:PASS:303:353,0,358:10,0:27,14

chr1	1227292	MantaDEL:39:0:0:0:0:0	GGCGGGAAGGCGAGCTCGTGGCCAGGCCCTGCGGGAAGGCGAGCTCGTGGCCAGGCCCGGCGGGAAGGCGAGCTCGTGGCCAGGCCCGGCGGGAAGGCGAGCTCGTGGCCAGGCCCGGCGGGAAGGCGAGCTCGTGGCCAGGCCCTGCGGGAAGGCGAGCTCGTGGCCAGGCCCT	G	322	PASS	END=1227466;SVTYPE=DEL;SVLEN=-174;CIGAR=1M174D;CIPOS=0,9;HOMLEN=9;HOMSEQ=GCGGGAAGG	GT:FT:GQ:PL:PR:SR	0/1:PASS:115:372,0,112:11,0:10,10

And I am sharing manta file after EvalSVcaller convertion:

chr1	66365	INS	.	.	999	PASS	SVTYPE=INS;SVLEN=146;READS=66;GT=0/1
chr1	831213	DEL	.	.	418	PASS	SVTYPE=DEL;SVLEN=2519;READS=19;GT=0/1
chr1	998763	INS	.	.	999	PASS	SVTYPE=INS;SVLEN=58;READS=47;GT=1/1
chr1	1207339	DEL	.	.	867	PASS	SVTYPE=DEL;SVLEN=421;READS=20;GT=0/1
chr1	1226336	DEL	.	.	303	PASS	SVTYPE=DEL;SVLEN=64;READS=14;GT=0/1

**Comment by stat-lab** [comment]
The input vcf file must contain a READS tag in the 8th column, which represents the number of reads supporting the SV.
As shown in README, your Manta output vcf should be converted with the command: scripts/convert_SV_callers_vcf.pl -t Manta [your Manta vcf] > out.vcf

**Comment by gamzemdn** [comment]
I did converted using scripts/convert_SV_callers_vcf.pl and here its first few lines are:


chr1 66365 INS . . 999 PASS SVTYPE=INS;SVLEN=146;READS=66;GT=0/1
chr1 831213 DEL . . 418 PASS SVTYPE=DEL;SVLEN=2519;READS=19;GT=0/1
chr1 998763 INS . . 999 PASS SVTYPE=INS;SVLEN=58;READS=47;GT=1/1
chr1 1207339 DEL . . 867 PASS SVTYPE=DEL;SVLEN=421;READS=20;GT=0/1
chr1 1226336 DEL . . 303 PASS SVTYPE=DEL;SVLEN=64;READS=14;GT=0/1

**Comment by stat-lab** [comment]
When using evaluate_SV_callers.pl, the reference vcf, except for NA12878 and SimA, must be specified with the -r2 option.

**Comment by gamzemdn** [comment]
My code is shown below:

'/home/EvalSVcallers-master/scripts/evaluate_SV_callers.pl'  -r2 '/home/HG00514_CHS_bionano_DLE1_annotatedSV_filtered_nonredundant.vcf'    '/home/manta.vcf'  -of 3 > hg00514_manta_overlap.vcf

I am still getting all FPs. I really wish to use this tool for my comparison of tool-reference pair.
Best,

**Comment by stat-lab** [comment]
Would you send me your Manta vcf and reference vcf files via email (shunichi.kosugi@nig.ac.jp)? If the file sizes are large, chromosome-specific ones are acceptable.

**Comment by gamzemdn** [comment]
Thank you for your support, I sent you all the required files and links about the big files such as cram, bam so that it might help you understand if I am doing something wrong. I really appreciate it.

Best,

**Comment by stat-lab** [comment]
Thank you for sending me your vcf files and the result files. I found a build 38-specific bug when outputting TP calls with the -of option in evaluate_SV_callers.pl. I have uploaded a fixed script, which you can try to use. Sorry for the confusion.

**Comment by gamzemdn** [comment]
Now I see all TP rows as well similar to SURVIVOR TP count. I believe this solves my problem. Thank you for all the help.

Best Regards,
