### ISSUE TITLE
"Use of uninitialized value $mate_pos in exists at" Error in SvABA convert run

### ISSUE THREAD

**Issue by gamzemdn** [stat-lab/EvalSVcallers#24]
Hi!

When I use SvABA script I get this error during conversion and it creates file with only INSERTIONS. I am sure there are other types of SVs. My svaba file is below. 

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	hg04036.bam
chr1	823176	20838091:1	T	]chr1:823659]T	20	PASS	DISC_MAPQ=41;EVDNC=DSCRD;IMPRECISE;MAPQ=41;MATEID=20838091:2;MATENM=-1;NM=-1;NUMPARTS=0;SCTG=chr1:823176(-)-chr1:823659(+)__1_808501_833501D;SPAN=483;SVTYPE=BND	GT:AD:DP:GQ:PL:SR:DR:LR:LO	0	0	11	0/1:11:58:20:20,0,125.6:0:11:-20.02:24.45

chr1	823659	20838091:2	C	C[chr1:823176[	20	PASS	DISC_MAPQ=29;EVDNC=DSCRD;IMPRECISE;MAPQ=29;MATEID=20838091:1;MATENM=-1;NM=-1;NUMPARTS=0;SCTG=chr1:823176(-)-chr1:823659(+)__1_808501_833501D;SPAN=483;SVTYPE=BND	GT:AD:DP:GQ:PL:SR:DR:LR:LO	0	0	11	0/1:11:58:20:20,0,125.6:0:11:-20.02:24.45

chr1	1289186	355023947:1	C	]chr1:1289644]C	27	PASS	DISC_MAPQ=19;EVDNC=DSCRD;IMPRECISE;MAPQ=19;MATEID=355023947:2;MATENM=-1;NM=-1;NUMPARTS=0;SCTG=chr1:1289186(-)-chr1:1289644(+)__1_1274001_1299001D;SPAN=458;SVTYPE=BND	GT:AD:DP:GQ:PL:SR:DR:LR:LO	0	0	11	0/1:11:33:27.2:27.2,0,53.6:0:11:-27.04:27.6

chr1	1289644	355023947:2	T	T[chr1:1289186[	27	PASS	DISC_MAPQ=18;EVDNC=DSCRD;IMPRECISE;MAPQ=18;MATEID=355023947:1;MATENM=-1;NM=-1;NUMPARTS=0;SCTG=chr1:1289186(-)-chr1:1289644(+)__1_1274001_1299001D;SPAN=458;SVTYPE=BND	GT:AD:DP:GQ:PL:SR:DR:LR:LO	0	0	11	0/1:11:33:27.2:27.2,0,53.6:0:11:-27.04:27.6

Thanks in advance

**Comment by stat-lab** [comment]
I uploaded a fixed convert_SvABA_vcf.pl script, and try to use it.

**Comment by gamzemdn** [comment]
Hello thank you for your quick response. I could convert my file with the new script but now I get the same error which I get with Gridss. Illegal division by zero at evaluate_SV_callers.pl line 1717. When I check that line I see division of reference dup so I checked my reference file and it has some duplications. I could use the same reference file in my other sample-caller combinations except SvABA and GRIDSS. I have another issue for GRIDSS by the way.

Line:
my $recall = int ((${$match_dup_num{'S'}}{$read} + $norecal) / ($ref_dup_s + $dup_ins_hit) * 1000) / 10;

**SvABA converted file:**
chr1	823176	DUP	.	.	.	PASS	SVTYPE=DUP;SVLEN=483;READS=2;GT=./.
chr1	1289186	DUP	.	.	.	PASS	SVTYPE=DUP;SVLEN=458;READS=3;GT=./.
chr1	1382269	DUP	.	.	.	PASS	SVTYPE=DUP;SVLEN=609;READS=4;GT=./.
chr1	1477855	DUP	.	.	.	PASS	SVTYPE=DUP;SVLEN=129;READS=6;GT=./.
chr1	1657089	DUP	.	.	.	PASS	SVTYPE=DUP;SVLEN=65281;READS=2;GT=./.
chr1	1934936	DEL	.	.	.	PASS	SVTYPE=DEL;SVLEN=638;READS=6;GT=./.

**Reference file:**

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Sample1
chr1	90556	SMAP1	N	<DUP>	.	PASS	SVTYPE=DUP;END=179202;SVLEN=88646;CIPOS=-9355,9355;CIEND=-4175,4175;EXPERIMENT=1	GT	./.

chr1	179202	SMAP2	N	<TRA>	1.94	PASS	SVTYPE=BND;CHR2=chr19;END=217202;SVLEN=0;CIPOS=-4175,4175;CIEND=-10327,10327;CT=+/+;EXPERIMENT=1	GT	0/1

chr1	90556	SMAP3	N	<DUP>	.	PASS	SVTYPE=DUP;END=179202;SVLEN=88646;CIPOS=-9355,9355;CIEND=-4175,4175;EXPERIMENT=1	GT	./.

chr1	179202	SMAP4	N	<TRA>	1.94	PASS	
SVTYPE=BND;CHR2=chr19;END=217202;SVLEN=0;CIPOS=-4175,4175;CIEND=-10327,10327;CT=+/+;EXPERIMENT=1	GT	0/1

**Comment by stat-lab** [comment]
This error is due to the absence of the S size of DUPs in your reference vcf. A fixed evaluate_SV_callers.pl script was uploaded. Also, I uploaded a fixed convert_SvABA_vcf.pl script again, which could display the genotypes normally.

**Comment by gamzemdn** [comment]
I completed my analysis without any error. Thank you so much...

Best Regards
