### ISSUE TITLE
Illegal division by zero at evaluate_SV_callers.pl line 1717.

### ISSUE THREAD

**Issue by gamzemdn** [stat-lab/EvalSVcallers#25]
Hi!

I am using Gridss caller outputs to evaluate my SVs. I had successful evaluation with all my samples except hg02059. I get this error while trying to evaluate my converted gridss file. Here is couple of lines from my Eval converted file and the reference file I am using. Surprisingly I had no trouble with my samples in other callers (Delly, Lumpy, Breakdancer, Manta, Wham) except SvABA (I have another issue opened for that)

chr1	820836	.	.	.	93	LOW_QUAL;SINGLE_ASSEMBLY	SVTYPE=DEL;SVLEN=37;READS=4
chr1	893791	.	.	.	2066	PASS	SVTYPE=DEL;SVLEN=36;READS=12
chr1	907836	.	.	.	2079	PASS	SVTYPE=DUP;SVLEN=31;READS=12
chr1	948671	.	.	.	1512	PASS	SVTYPE=DUP;SVLEN=40;READS=10
chr1	964544	.	.	.	50	LOW_QUAL;SINGLE_ASSEMBLY	SVTYPE=DEL;SVLEN=222;READS=4
chr1	964566	.	.	.	102	LOW_QUAL;SINGLE_ASSEMBLY	SVTYPE=DEL;SVLEN=152;READS=5
chr1	991434	.	.	.	246	LOW_QUAL	SVTYPE=DEL;SVLEN=340;READS=5
chr1	998744	.	.	.	504	SINGLE_ASSEMBLY	SVTYPE=DUP;SVLEN=51;READS=7
chr1	1029398	.	.	.	170	LOW_QUAL;SINGLE_ASSEMBLY	SVTYPE=DUP;SVLEN=30;READS=5
chr1	1067274	.	.	.	230	LOW_QUAL;SINGLE_ASSEMBLY	SVTYPE=INV;SVLEN=1475;READS=5
chr1	1068752	.	.	.	1180	PASS	SVTYPE=DUP;SVLEN=77;READS=9
chr1	1099080	.	.	.	260	LOW_QUAL;SINGLE_ASSEMBLY	SVTYPE=DEL;SVLEN=378;READS=5
chr1	1109048	.	.	.	298	LOW_QUAL;SINGLE_ASSEMBLY	SVTYPE=DEL;SVLEN=30;READS=5
chr1	1109111	.	.	.	510	NO_ASSEMBLY	SVTYPE=DEL;SVLEN=31;READS=7

**My reference file is HG02059.HGSVC.20210928.bionano.vcf downloaded from:** https://ftp.sra.ebi.ac.uk/1000g/ftp/data_collections/HGSVC2/working/20210902_bionano_hgsvc/HG02059/

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Sample1

chr1	179202	SMAP1	N	<TRA>	1.87	PASS	SVTYPE=BND;CHR2=chr19;END=217202;SVLEN=0;CIPOS=-4175,4175;CIEND=-10327,10327;CT=+/+;EXPERIMENT=1	GT	0/1

chr1	179202	SMAP2	N	<TRA>	1.87	PASS	SVTYPE=BND;CHR2=chr19;END=217202;SVLEN=0;CIPOS=-4175,4175;CIEND=-10327,10327;CT=+/+;EXPERIMENT=1	GT	0/1

chr1	376383	SMAP3	N	<INS>	20	PASS	SVTYPE=INS;END=376383;SVLEN=5336;CIPOS=-10848,10848;CIEND=-10848,10848;EXPERIMENT=1	GT	1/1

chr1	376383	SMAP5	N	<INS>	20	PASS	SVTYPE=INS;END=376383;SVLEN=5336;CIPOS=-10848,10848;CIEND=-10848,10848;EXPERIMENT=1	GT	1/1

chr1	667970	SMAP7	N	<INS>	.	PASS	SVTYPE=INS;END=667970;SVLEN=442;CIPOS=-4109,4109;CIEND=-4109,4109;EXPERIMENT=1	GT	1/1

**Comment by stat-lab** [comment]
This error is due to the absence of the S size of DUPs in your reference vcf. A fixed evaluate_SV_callers.pl script was uploaded, and try to use it.

**Comment by gamzemdn** [comment]
It works! Thank you so much...
