### ISSUE TITLE
Wrong directory! 

### ISSUE THREAD

**Issue by spsc83** [stat-lab/EvalSVcallers#5]
When I tried the example of the converting step, I got this:
[myname@loginnode1 EvalSVcallers]$ scripts/convert_SV_callers_vcf.pl -t Pindel pindel.DEL.out pindel.DUP.out > Pindel.vcf
TOOL name specified is absent in 69 tools we analyzed or does not match the names:

I checked the Perl code. And I guess line 47 of scripts/convert_SV_callers_vcf.pl should be like this:
my @convert_script = <$script_path/vcf_convert/convert_$tool*.pl>;

**Comment by stat-lab** [comment]
> When I tried the example of the converting step, I got this:
> [myname@loginnode1 EvalSVcallers]$ scripts/convert_SV_callers_vcf.pl -t Pindel pindel.DEL.out pindel.DUP.out > Pindel.vcf
> TOOL name specified is absent in 69 tools we analyzed or does not match the names:
> 
> I checked the Perl code. And I guess line 47 of scripts/convert_SV_callers_vcf.pl should be like this:
> my @convert_script = <$script_path/vcf_convert/convert_$tool*.pl>;

Sorry for delay of my response. The script, convert_SV_callers_vcf.pl, was fixed to correctly assign the vcf_convert subdirectory.
