### ISSUE TITLE
VCF conversion fails for CNVnator and Manta

### ISSUE THREAD

**Issue by bioinfo89** [stat-lab/EvalSVcallers#6]
Hi,

I am using the convert_SV_callers_vcf.pl for Delly, Lumpy, Manta and CNVnator output files (All VCFs). It works fine for Delly and Lumpy VCF files but I don't get any output for Manta (diploid VCF) and CNVnator files, the files are empty and there is no error message also while running it.

I am not sure what went wrong. Any help would be appreciated.

**Comment by stat-lab** [comment]
I uploaded a fixed script of ‘convert_CNVnator_vcf.pl’, which had contained a wrong path of the gap.bed file. But I’m not sure why the Manta conversion did not go well. Have you used a diploidSV.vcf.gz file for the Manta output? If you so, could you send it to me?

**Comment by bioinfo89** [comment]
I did change the path to gap.bed in the CNVnator script before using it. Yes, I used diploidSV.vcf.gz file as input. Sending you Manta files via email.

Thanks!

**Comment by stat-lab** [comment]
The problem was attributed to the reference chromosome names based on the hg19 reference, which has 'chr' prefix in the chromosome names. This evaluation system has been developed with the GRCh37 reference. I changed all the scripts so that the hg19-based files can be used for the evaluation.
