### ISSUE TITLE
evaluate_SV_overlap_calls.pl fails to find Delly vcf

### ISSUE THREAD

**Issue by bioinfo89** [stat-lab/EvalSVcallers#7]
Hi,

I am using evaluate_SV_overlap_calls.pl to evaluate Delly and Lumpy SV calls against NA12878 reference sets, and I use the following command:

perl EvalSVcallers/scripts/evaluate_SV_overlap_calls.pl -r N -t Delly:3 Lumpy:5 -p Delly-Lumpy-overlap -vcf -d ./

I get the following error: vcf file for Delly is not found:

though both the vcfs are in the same folder.

Am I doing something wrong here?

**Comment by stat-lab** [comment]
Please send me the Delly vcf file converted with the convert_SV_callers_vcf.pl script (shunichi.kosugi@riken.jp).

**Comment by stat-lab** [comment]
The problem was attributed to the reference chromosome names based on the hg19 reference, which has 'chr' prefix in the chromosome names. This evaluation system has been developed with the GRCh37 reference. I changed all the scripts so that the hg19-based files can be used for the evaluation.

**Comment by tyyiyi** [comment]
I ran into the same problem when running evaluate_SV_overlap_calls.pl. It gave me the error :
![image](https://user-images.githubusercontent.com/48273651/147896799-15b6759a-3894-4229-831e-429372b675ae.png)
my command is 
![image](https://user-images.githubusercontent.com/48273651/147896824-e3d8edec-b566-4daa-9837-e76d47dcd0e0.png)
my delly and lumpy vcf files are in 
![image](https://user-images.githubusercontent.com/48273651/147896858-6ec1333e-1502-4934-86d2-ed0088f482f3.png)
can you give me a help？
Thank you！
